[package]
name = "prosto-dummy"
version = "0.0.1"
edition = "2018"

[dependencies]
prost = "0.6"

[dev-dependencies]
prosto = { path = "../" }
rand = "0.8"
tracing-subscriber = "0.2"
proptest = "0.10"
tokio = { version = "0.2", features = ["rt-threaded", "sync"]}
tonic = "0.4"
anyhow = "1.0"

[build-dependencies]
tonic-build = { version = "0.3", default-features = false, features = ["transport", "prost"] }
